const GET_MATERIALS = 'GET_MATERIALS';
const GET_MATERIALS_SUCCEED = 'GET_MATERIALS_SUCCEED';
const GET_MATERIALS_FAILED = 'GET_MATERIALS_FAILED';

const DELETE_MATERIALS = 'DELETE_MATERIALS';
const DELETE_MATERIALS_SUCCEED = 'DELETE_MATERIALS_SUCCEED';
const DELETE_MATERIALS_FAILED = 'DELETE_MATERIALS_FAILED';

const DELETE_SELECTED_LISTS = 'DELETE_SELECTED_LISTS';

const SET_SEARCH_PARAMS = 'SET_SEARCH_PARAMS';

const CHECK_RESOURCE_BY_PARAMS = 'CHECK_RESOURCE_BY_PARAMS';
const CHECK_RESOURCE_BY_PARAMS_SUCCEED = 'CHECK_RESOURCE_BY_PARAMS_SUCCEED';
const CHECK_RESOURCE_BY_PARAMS_FAILED = 'CHECK_RESOURCE_BY_PARAMS_FAILED';

const CHECK_RESOURCE_BY_IDS = 'CHECK_RESOURCE_BY_IDS';
const CHECK_RESOURCE_BY_IDS_FAILED = 'CHECK_RESOURCE_BY_IDS_FAILED';
const CHECK_RESOURCE_BY_IDS_SUCCEED = 'CHECK_RESOURCE_BY_IDS_SUCCEED';

const DELETE_RESOURCE_BY_PARAMS = 'DELETE_RESOURCE_BY_PARAMS';

const DELETE_RESOURCE_BY_IDS = 'DELETE_RESOURCE_BY_IDS';

const EXPORT_RESOURCE_BY_PARAMS = 'EXPORT_RESOURCE_BY_PARAMS';

const EXPORT_RESOURCE_BY_IDS = 'EXPORT_RESOURCE_BY_IDS';

const GET_TEXT_LIST = 'GET_TEXT_LIST';
const GET_TEXT_LIST_SUCCEED = 'GET_TEXT_LIST_SUCCEED';
const GET_TEXT_LIST_FAILED = 'GET_TEXT_LIST_FAILED';

const DELETE_TEXT = 'DELETE_TEXT';
const DELETE_TEXT_SUCCEED = 'DELETE_TEXT_SUCCEED';
const DELETE_TEXT_FAILED = 'DELETE_TEXT_FAILED';

const ADD_TEXT = 'ADD_TEXT';
const ADD_TEXT_SUCCEED = 'ADD_TEXT_SUCCEED';
const ADD_TEXT_FAILED = 'ADD_TEXT_FAILED';

const UPDATE_TEXT = 'UPDATE_TEXT';
const UPDATE_TEXT_SUCCEED = 'UPDATE_TEXT_SUCCEED';
const UPDATE_TEXT_FAILED = 'UPDATE_TEXT_FAILED';

const GET_SUBTEXT_LIST = 'GET_SUBTEXT_LIST';
const GET_SUBTEXT_LIST_SUCCEED = 'GET_SUBTEXT_LIST_SUCCEED';
const GET_SUBTEXT_LIST_FAILED = 'GET_SUBTEXT_LIST_FAILED';

const GET_TAGS = 'GET_TAGS';
const GET_TAGS_SUCCEED = 'GET_TAGS_SUCCEED';
const GET_TAGS_FAILED = 'GET_TAGS_FAILED';

const GET_PICTURE = 'GET_PICTURE';
const GET_PICTURE_SUCCEED = 'GET_PICTURE_SUCCEED';
const GET_PICTURE_FAILED = 'GET_PICTURE_FAILED';

const GET_LINKLIST = 'GET_LINKLIST';
const GET_LINKLIST_SUCCEED = 'GET_LINKLIST_SUCCEED';
const GET_LINKLIST_FAILED = 'GET_LINKLIST_FAILED';

const GET_COMMENTLIST = 'GET_COMMENTLIST';
const GET_COMMENTLIST_SUCCEED = 'GET_COMMENTLIST_SUCCEED';
const GET_COMMENTLIST_FAILED = 'GET_COMMENTLIST_FAILED';

const ADD_COMMENT = 'ADD_COMMENT';
const ADD_COMMENT_SUCCEED = 'ADD_COMMENT_SUCCEED';
const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';

const DELETE_COMMENT = 'DELETE_COMMENT';
const DELETE_COMMENT_SUCCEED = 'DELETE_COMMENT_SUCCEED';
const DELETE_COMMENT_FAILED = 'DELETE_COMMENT_FAILED';

const UPDATE_COMMENT = 'UPDATE_COMMENT';
const UPDATE_COMMENT_SUCCEED = 'UPDATE_COMMENT_SUCCEED';
const UPDATE_COMMENT_FAILED = 'UPDATE_COMMENT_FAILED';

const MATERIAL_2_WX_SETTING = 'MATERIAL_2_WX_SETTING';
const GENERATE_BY_HAND = 'GENERATE_BY_HAND';
const GENERATE_BY_HAND_SUCCEED = 'GENERATE_BY_HAND_SUCCEED';
const GENERATE_BY_HAND_FAILED = 'GENERATE_BY_HAND_FAILED';

const GENERATE_BY_AUTO = 'GENERATE_BY_AUTO';
const GENERATE_BY_AUTO_SUCCEED = 'GENERATE_BY_AUTO_SUCCEED';
const GENERATE_BY_AUTO_FAILED = 'GENERATE_BY_AUTO_FAILED';

const EXPORT_MATERIALS_BY_HAND = 'EXPORT_MATERIALS_BY_HAND';
const EXPORT_MATERIALS_BY_HAND_SUCCEED = 'EXPORT_MATERIALS_BY_HAND_SUCCEED';
const EXPORT_MATERIALS_BY_HAND_FAILED = 'EXPORT_MATERIALS_BY_HAND_FAILED';

const EXPORT_MATERIALS_BY_IDS = 'EXPORT_MATERIALS_BY_IDS';
const EXPORT_MATERIALS_BY_IDS_SUCCEED = 'EXPORT_MATERIALS_BY_IDS_SUCCEED';
const EXPORT_MATERIALS_BY_IDS_FAILED = 'EXPORT_MATERIALS_BY_IDS_FAILED'

const WX_TASK_ACTIVE_TAB = 'WX_TASK_ACTIVE_TAB';

const GET_WX_TASK = 'GET_WX_TASK';
const GET_WX_TASK_SUCCESS = 'GET_WX_TASK_SUCCESS';
const GET_WX_TASK_ERROR = 'GET_WX_TASK_ERROR';

const DELETE_WX_TASK = 'DELETE_WX_TASK';
const DELETE_WX_TASK_SUCCESS = 'DELETE_WX_TASK_SUCCESS';
const DELETE_WX_TASK_ERROR = 'DELETE_WX_TASK_ERROR';

const CANCEL_WX_TASK = 'CANCEL_WX_TASK';
const CANCEL_WX_TASK_SUCCESS = 'CANCEL_WX_TASK_SUCCESS';
const CANCEL_WX_TASK_ERROR = 'CANCEL_WX_TASK_ERROR';

const RESEND_WX_TASK = 'RESEND_WX_TASK';
const RESEND_WX_TASK_SUCCESS = 'RESEND_WX_TASK_SUCCESS';
const RESEND_WX_TASK_ERROR = 'RESEND_WX_TASK_ERROR';

const GET_TASK_LISTS = 'GET_TASK_LISTS';
const GET_TASK_LISTS_SUCCESS = 'GET_TASK_LISTS_SUCCESS';
const GET_TASK_LISTS_ERROR = 'GET_TASK_LISTS_ERROR';

const GET_ROBOT = 'GET_ROBOT';
const GET_ROBOT_SUCCESS = 'GET_ROBOT_SUCCESS';
const GET_ROBOT_ERROR = 'GET_ROBOT_ERROR';

// 点赞
const LIKE_MOMENT = 'LIKE_MOMENT';
const LIKE_MOMENT_SUCCEED = 'LIKE_MOMENT_SUCCEED';
const LIKE_MOMENT_FAILED = 'LIKE_MOMENT_FAILED';

// 删除已点赞
const DISLIKE_MOMENT = 'DISLIKE_MOMENT';
const DISLIKE_MOMENT_SUCCEED = 'DISLIKE_MOMENT_SUCCEED';
const DISLIKE_MOMENT_FAILED = 'DISLIKE_MOMENT_FAILED';

// 评论
const COMMENT_MOMENT = 'COMMENT_MOMENT';
const COMMENT_MOMENT_SUCCEED = 'COMMENT_MOMENT_SUCCEED';
const COMMENT_MOMENT_FAILED = 'COMMENT_MOMENT_FAILED';

// 获取朋友圈
const GET_MOMENTS = 'GET_MOMENTS';
const GET_ALL_MOMENTS_SUCCEED = 'GET_ALL_MOMENTS_SUCCEED';
const GET_MINE_MOMENTS_SUCCEED = 'GET_MINE_MOMENTS_SUCCEED';
const GET_ALL_MOMENTS_FAILED = 'GET_ALL_MOMENTS_FAILED';
const GET_MINE_MOMENTS_FAILED = 'GET_MINE_MOMENTS_FAILED';

// 获取更新通知
const GET_UPDATED_NOTICE = 'GET_UPDATED_NOTICE';
const GET_UPDATED_NOTICE_SUCCEED = 'GET_UPDATED_NOTICE_SUCCEED';
const GET_UPDATED_NOTICE_FAILED = 'GET_UPDATED_NOTICE_FAILED';

// 移除已查看的通知
const REMOVE_CHECKED_NOTICE = 'REMOVE_CHECKED_NOTICE';
const REMOVE_CHECKED_NOTICE_SUCCEED = 'REMOVE_CHECKED_NOTICE_SUCCEED';
const REMOVE_CHECKED_NOTICE_FAILED = 'REMOVE_CHECKED_NOTICE_FAILED';

// 获取更新的朋友圈
const GET_UPDATED_MOMENT = 'GET_UPDATED_MOMENT';
const GET_UPDATED_MOMENT_SUCCEED = 'GET_UPDATED_MOMENT_SUCCEED';
const GET_UPDATED_MOMENT_FAILED = 'GET_UPDATED_MOMENT_FAILED';

// 获取更新的朋友圈详情
const GET_UPDATED_DETAILS = 'GET_UPDATED_DETAILS';
const GET_UPDATED_DETAILS_SUCCEED = 'GET_UPDATED_DETAILS_SUCCEED';
const GET_UPDATED_DETAILS_FAILED = 'GET_UPDATED_DETAILS_FAILED';

// 删除朋友圈
const DELETE_MOMENT = 'DELETE_MOMENT';
const DELETE_MOMENT_SUCCEED = 'DELETE_MOMENT_SUCCEED';
const DELETE_MOMENT_FAILED = 'DELETE_MOMENT_FAILED';

// 删除朋友圈点赞或评论
const DELETE_MOMENT_COMMENT = 'DELETE_MOMENT_COMMENT';
const DELETE_MOMENT_COMMENT_SUCCEED = 'DELETE_MOMENT_COMMENT_SUCCEED';
const DELETE_MOMENT_COMMENT_FAILED = 'DELETE_MOMENT_COMMENT_FAILED';

// 取消朋友圈点赞或评论
const CANCEL_MOMENT_COMMENT = 'CANCEL_MOMENT_COMMENT';
const CANCEL_MOMENT_COMMENT_SUCCEED = 'CANCEL_MOMENT_COMMENT_SUCCEED';
const CANCEL_MOMENT_COMMENT_FAILED = 'CANCEL_MOMENT_COMMENT_FAILED';

// 更新朋友圈“是否有更多”
const UPDATE_HASMORE = 'UPDATE_HASMORE';
const UPDATE_HASMORE_SUCCEED = 'UPDATE_HASMORE_SUCCEED';
const UPDATE_HASMORE_FAILED = 'UPDATE_HASMORE_FAILED';
const GET_ROBOT_MATERIAL = 'GET_ROBOT_MATERIAL';
const GET_ROBOT_MATERIAL_SUCCESS = 'GET_ROBOT_MATERIAL_SUCCESS';
const GET_ROBOT_MATERIAL_ERROR = 'GET_ROBOT_MATERIAL_ERROR';

// 全局操作错误的type
const OPERATE_FAILED = 'OPERATE_FAILED';

// 切换个人号之前的朋友圈初始化操作
const INIT_MOMENT = 'INIT_MOMENT';
// 初始化一：朋友圈
const CLEAR_MOMENT = 'CLEAR_MOMENT';
// 初始化二：分页状态
const INIT_HASMORE = 'INIT_HASMORE';
// 初始化三：清空分页通知
const CLEAR_NOTICE = 'CLEAR_NOTICE';

// 更改loading状态
const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS'

// 更改单个朋友圈状态
const CHANGE_ONE_LOADING_STATUS = 'CHANGE_ONE_LOADING_STATUS'

export default {
  GET_MATERIALS,
  GET_MATERIALS_SUCCEED,
  GET_MATERIALS_FAILED,
  DELETE_MATERIALS,
  DELETE_MATERIALS_SUCCEED,
  DELETE_MATERIALS_FAILED,
  DELETE_SELECTED_LISTS,
  SET_SEARCH_PARAMS,
  CHECK_RESOURCE_BY_PARAMS,
  CHECK_RESOURCE_BY_PARAMS_SUCCEED,
  CHECK_RESOURCE_BY_PARAMS_FAILED,
  CHECK_RESOURCE_BY_IDS,
  DELETE_RESOURCE_BY_PARAMS,
  DELETE_RESOURCE_BY_IDS,
  EXPORT_RESOURCE_BY_PARAMS,
  EXPORT_RESOURCE_BY_IDS,
  GET_TEXT_LIST,
  GET_TEXT_LIST_SUCCEED,
  GET_TEXT_LIST_FAILED,
  DELETE_TEXT,
  DELETE_TEXT_SUCCEED,
  DELETE_TEXT_FAILED,
  ADD_TEXT,
  UPDATE_TEXT,
  UPDATE_TEXT_SUCCEED,
  UPDATE_TEXT_FAILED,
  ADD_TEXT_SUCCEED,
  ADD_TEXT_FAILED,
  GET_SUBTEXT_LIST,
  GET_SUBTEXT_LIST_SUCCEED,
  GET_SUBTEXT_LIST_FAILED,
  GET_TAGS,
  GET_TAGS_SUCCEED,
  GET_TAGS_FAILED,
  GET_PICTURE,
  GET_PICTURE_SUCCEED,
  GET_PICTURE_FAILED,
  GET_LINKLIST,
  GET_LINKLIST_SUCCEED,
  GET_LINKLIST_FAILED,
  GET_COMMENTLIST,
  GET_COMMENTLIST_SUCCEED,
  GET_COMMENTLIST_FAILED,
  MATERIAL_2_WX_SETTING,
  GENERATE_BY_HAND,
  GENERATE_BY_HAND_SUCCEED,
  GENERATE_BY_HAND_FAILED,
  GENERATE_BY_AUTO,
  GENERATE_BY_AUTO_SUCCEED,
  GENERATE_BY_AUTO_FAILED,
  ADD_COMMENT,
  ADD_COMMENT_SUCCEED,
  ADD_COMMENT_FAILED,
  DELETE_COMMENT,
  DELETE_COMMENT_SUCCEED,
  DELETE_COMMENT_FAILED,
  UPDATE_COMMENT,
  UPDATE_COMMENT_SUCCEED,
  UPDATE_COMMENT_FAILED,
  EXPORT_MATERIALS_BY_HAND,
  EXPORT_MATERIALS_BY_HAND_SUCCEED,
  EXPORT_MATERIALS_BY_HAND_FAILED,
  EXPORT_MATERIALS_BY_IDS,
  EXPORT_MATERIALS_BY_IDS_SUCCEED,
  EXPORT_MATERIALS_BY_IDS_FAILED,
  GET_WX_TASK,
  GET_WX_TASK_SUCCESS,
  GET_WX_TASK_ERROR,
  DELETE_WX_TASK,
  DELETE_WX_TASK_SUCCESS,
  DELETE_WX_TASK_ERROR,
  CANCEL_WX_TASK,
  CANCEL_WX_TASK_SUCCESS,
  CANCEL_WX_TASK_ERROR,
  RESEND_WX_TASK,
  RESEND_WX_TASK_SUCCESS,
  RESEND_WX_TASK_ERROR,
  WX_TASK_ACTIVE_TAB,
  GET_TASK_LISTS,
  GET_TASK_LISTS_SUCCESS,
  GET_TASK_LISTS_ERROR,
  CHECK_RESOURCE_BY_IDS_FAILED,
  CHECK_RESOURCE_BY_IDS_SUCCEED,
  GET_ROBOT,
  GET_ROBOT_SUCCESS,
  GET_ROBOT_ERROR,
  LIKE_MOMENT,
  LIKE_MOMENT_SUCCEED,
  LIKE_MOMENT_FAILED,
  COMMENT_MOMENT,
  COMMENT_MOMENT_SUCCEED,
  COMMENT_MOMENT_FAILED,
  GET_MOMENTS,
  GET_ALL_MOMENTS_SUCCEED,
  GET_MINE_MOMENTS_SUCCEED,
  GET_ALL_MOMENTS_FAILED,
  GET_MINE_MOMENTS_FAILED,
  GET_UPDATED_MOMENT,
  GET_UPDATED_MOMENT_SUCCEED,
  GET_UPDATED_MOMENT_FAILED,
  GET_UPDATED_NOTICE,
  GET_UPDATED_NOTICE_SUCCEED,
  GET_UPDATED_NOTICE_FAILED,
  GET_UPDATED_DETAILS,
  GET_UPDATED_DETAILS_SUCCEED,
  GET_UPDATED_DETAILS_FAILED,
  DELETE_MOMENT,
  DELETE_MOMENT_SUCCEED,
  DELETE_MOMENT_FAILED,
  DELETE_MOMENT_COMMENT,
  DELETE_MOMENT_COMMENT_SUCCEED,
  DELETE_MOMENT_COMMENT_FAILED,
  CANCEL_MOMENT_COMMENT,
  CANCEL_MOMENT_COMMENT_SUCCEED,
  CANCEL_MOMENT_COMMENT_FAILED,
  UPDATE_HASMORE,
  UPDATE_HASMORE_SUCCEED,
  UPDATE_HASMORE_FAILED,
  GET_ROBOT_MATERIAL,
  GET_ROBOT_MATERIAL_SUCCESS,
  GET_ROBOT_MATERIAL_ERROR,
  REMOVE_CHECKED_NOTICE,
  REMOVE_CHECKED_NOTICE_SUCCEED,
  REMOVE_CHECKED_NOTICE_FAILED,
  OPERATE_FAILED,
  DISLIKE_MOMENT,
  DISLIKE_MOMENT_SUCCEED,
  DISLIKE_MOMENT_FAILED,
  INIT_MOMENT,
  CLEAR_MOMENT,
  INIT_HASMORE,
  CLEAR_NOTICE,
  CHANGE_LOADING_STATUS,
  CHANGE_ONE_LOADING_STATUS,
}